spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: 1234
    url: jdbc:oracle:thin:@localhost:1521/orclpdb
    username: SYSTEM
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        validator:
          apply_to_ddl: false